sudo: false
language: python
python:
  - "3.9"
# command to install dependencies
install:
before_script:
  - pip install tox-travis
  - pip install coveralls
# command to run tests
script: tox
after_success: coveralls